services:
  solar_api:
    image: planetev_solar_pm_service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m app.main
    
    ports:
      - "5002:5000"
    restart: always
    env_file:
      - .env
    networks:
      - solar_network
    volumes:
      - .:/app

  mongodb:
    container_name: planetev_solar_mongodb
    image: mongo:8.0.3
    restart: always
    command:
      - --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: pnevadmin
      MONGO_INITDB_ROOT_PASSWORD: pca1234
      MONGO_INITDB_DATABASE: iot
    ports:
      - "28000:27017"
    volumes:
      - planetev_solar_mongodb:/data/db
      - planetev_solar_mongodb:/var/log/mongodb/
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - solar_network

volumes:
  planetev_solar_mongodb:
  planetev_solar_mongodb_log:

networks:
  solar_network:

